### ISSUE TITLE
想问下，如何实现第一个元素不能被拖拽

### ISSUE THREAD

**Issue by lianghuiboy** [mengxianliang/XLChannelControl#1]
想问下，如何实现第一个元素不能被拖拽，要做哪几步？

**Comment by mengxianliang** [comment]
你好，刚才改动了一下，固定了第一个元素不可拖拽、删除。

**Comment by bolianghui** [comment]
我刚才调试了一下，你的第一个元素还是可以被交换。不是固定的。

**Comment by lianghuiboy** [comment]
你好，你的改动，我调试了，还是可以被交换元素。没有固定。






在 2017-05-04 11:56:39，"XianLiang Meng" <notifications@github.com> 写道：


你好，刚才改动了一下，固定了第一个元素不可拖拽、删除。

**Comment by lianghuiboy** [comment]
不过我已经自己修好了，在XLChannelView的-(void)dragChanged:(CGPoint)point里面，更新数据源的加个判断_targetIndexPath.row != 0，就OK了。

**Comment by mengxianliang** [comment]
我试了一下确实如此，当时疏忽了，谢谢你的提醒。
