### ISSUE TITLE
你好   频道管理可以做存储吗    就像 存手机数据库一样的  在app 首次安装的时候创建

### ISSUE THREAD

**Issue by 18667366881** [mengxianliang/XLChannelControl#3]
您好   频道管理可以做存储吗    就像 存手机数据库一样的  在app 首次安装的时候创建  后面修改的数据 存储起来  改变导航条的数据

**Comment by mengxianliang** [comment]
按照新闻客户端的业务逻辑应该是做一个本地表来保存频道信息的。本地数据库数据模块需要你单独写的，我写的这个只是负责UI模块，和数据不冲突。你可以在显示频道管理界面前先读本地数据库里的信息，然后排序后再更新本地数据库。然后导航条上的栏目信息也是直接读取本地数据库中的数据，和频道管理的UI不冲突。

**Comment by 18667366881** [comment]
那可以获取到您     排序后的数据吗   目前看来稍微有些看不懂  呵呵

**Comment by mengxianliang** [comment]
[[XLChannelControl shareControl] showChannelViewWithInUseTitles:titleArr1 unUseTitles:titleArr2 finish:^(NSArray *inUseTitles, NSArray *unUseTitles) {
    //处理后续问题
}];
这里的block回调中返回了两个集合，inUseTitles代表排序后的“已选频道”。unUseTitles代表“未选频道”。

**Comment by xws182** [comment]
[_inUseTitles removeObjectAtIndex:indexPath.row];//此方法解决重复的标签，移除会崩溃的bug
[_unUseTitles removeObjectAtIndex:indexPath.row];//此方法解决重复的标签，移除会崩溃的bug
[_inUseTitles removeObjectAtIndex:_dragingIndexPath.row];//此方法解决重复的标签，拖拽会崩溃的bug

**Comment by mengxianliang** [comment]
好的，谢谢。
